[pytest]
filterwarnings =
    ignore::DeprecationWarning:werkzeug
    ignore::DeprecationWarning:flask
    ignore::DeprecationWarning:google.protobuf
    ignore::DeprecationWarning:ast
    ignore::PendingDeprecationWarning
addopts = --tb=short
testpaths = tests
norecursedirs = tests/tracking_benchmark
