# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import tracking_pb2 as tracking__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tracking_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrackingServiceStub(object):
    """RWS Tracking gRPC Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/rws_tracking.TrackingService/HealthCheck',
                request_serializer=tracking__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=tracking__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.StartTracking = channel.unary_unary(
                '/rws_tracking.TrackingService/StartTracking',
                request_serializer=tracking__pb2.StartTrackingRequest.SerializeToString,
                response_deserializer=tracking__pb2.StartTrackingResponse.FromString,
                _registered_method=True)
        self.StopTracking = channel.unary_unary(
                '/rws_tracking.TrackingService/StopTracking',
                request_serializer=tracking__pb2.StopTrackingRequest.SerializeToString,
                response_deserializer=tracking__pb2.StopTrackingResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/rws_tracking.TrackingService/GetStatus',
                request_serializer=tracking__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=tracking__pb2.GetStatusResponse.FromString,
                _registered_method=True)
        self.SetGimbalPosition = channel.unary_unary(
                '/rws_tracking.TrackingService/SetGimbalPosition',
                request_serializer=tracking__pb2.SetGimbalPositionRequest.SerializeToString,
                response_deserializer=tracking__pb2.SetGimbalPositionResponse.FromString,
                _registered_method=True)
        self.SetGimbalRate = channel.unary_unary(
                '/rws_tracking.TrackingService/SetGimbalRate',
                request_serializer=tracking__pb2.SetGimbalRateRequest.SerializeToString,
                response_deserializer=tracking__pb2.SetGimbalRateResponse.FromString,
                _registered_method=True)
        self.GetTelemetry = channel.unary_unary(
                '/rws_tracking.TrackingService/GetTelemetry',
                request_serializer=tracking__pb2.GetTelemetryRequest.SerializeToString,
                response_deserializer=tracking__pb2.GetTelemetryResponse.FromString,
                _registered_method=True)
        self.UpdateConfig = channel.unary_unary(
                '/rws_tracking.TrackingService/UpdateConfig',
                request_serializer=tracking__pb2.UpdateConfigRequest.SerializeToString,
                response_deserializer=tracking__pb2.UpdateConfigResponse.FromString,
                _registered_method=True)
        self.StreamStatus = channel.unary_stream(
                '/rws_tracking.TrackingService/StreamStatus',
                request_serializer=tracking__pb2.StreamStatusRequest.SerializeToString,
                response_deserializer=tracking__pb2.StatusUpdate.FromString,
                _registered_method=True)


class TrackingServiceServicer(object):
    """RWS Tracking gRPC Service
    """

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartTracking(self, request, context):
        """Start tracking
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopTracking(self, request, context):
        """Stop tracking
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Get status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetGimbalPosition(self, request, context):
        """Set gimbal position (absolute)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetGimbalRate(self, request, context):
        """Set gimbal rate (velocity)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTelemetry(self, request, context):
        """Get telemetry
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConfig(self, request, context):
        """Update configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamStatus(self, request, context):
        """Stream status updates (real-time)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrackingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=tracking__pb2.HealthCheckRequest.FromString,
                    response_serializer=tracking__pb2.HealthCheckResponse.SerializeToString,
            ),
            'StartTracking': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTracking,
                    request_deserializer=tracking__pb2.StartTrackingRequest.FromString,
                    response_serializer=tracking__pb2.StartTrackingResponse.SerializeToString,
            ),
            'StopTracking': grpc.unary_unary_rpc_method_handler(
                    servicer.StopTracking,
                    request_deserializer=tracking__pb2.StopTrackingRequest.FromString,
                    response_serializer=tracking__pb2.StopTrackingResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=tracking__pb2.GetStatusRequest.FromString,
                    response_serializer=tracking__pb2.GetStatusResponse.SerializeToString,
            ),
            'SetGimbalPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.SetGimbalPosition,
                    request_deserializer=tracking__pb2.SetGimbalPositionRequest.FromString,
                    response_serializer=tracking__pb2.SetGimbalPositionResponse.SerializeToString,
            ),
            'SetGimbalRate': grpc.unary_unary_rpc_method_handler(
                    servicer.SetGimbalRate,
                    request_deserializer=tracking__pb2.SetGimbalRateRequest.FromString,
                    response_serializer=tracking__pb2.SetGimbalRateResponse.SerializeToString,
            ),
            'GetTelemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTelemetry,
                    request_deserializer=tracking__pb2.GetTelemetryRequest.FromString,
                    response_serializer=tracking__pb2.GetTelemetryResponse.SerializeToString,
            ),
            'UpdateConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConfig,
                    request_deserializer=tracking__pb2.UpdateConfigRequest.FromString,
                    response_serializer=tracking__pb2.UpdateConfigResponse.SerializeToString,
            ),
            'StreamStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamStatus,
                    request_deserializer=tracking__pb2.StreamStatusRequest.FromString,
                    response_serializer=tracking__pb2.StatusUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rws_tracking.TrackingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rws_tracking.TrackingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrackingService(object):
    """RWS Tracking gRPC Service
    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rws_tracking.TrackingService/HealthCheck',
            tracking__pb2.HealthCheckRequest.SerializeToString,
            tracking__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartTracking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rws_tracking.TrackingService/StartTracking',
            tracking__pb2.StartTrackingRequest.SerializeToString,
            tracking__pb2.StartTrackingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopTracking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rws_tracking.TrackingService/StopTracking',
            tracking__pb2.StopTrackingRequest.SerializeToString,
            tracking__pb2.StopTrackingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rws_tracking.TrackingService/GetStatus',
            tracking__pb2.GetStatusRequest.SerializeToString,
            tracking__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetGimbalPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rws_tracking.TrackingService/SetGimbalPosition',
            tracking__pb2.SetGimbalPositionRequest.SerializeToString,
            tracking__pb2.SetGimbalPositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetGimbalRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rws_tracking.TrackingService/SetGimbalRate',
            tracking__pb2.SetGimbalRateRequest.SerializeToString,
            tracking__pb2.SetGimbalRateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rws_tracking.TrackingService/GetTelemetry',
            tracking__pb2.GetTelemetryRequest.SerializeToString,
            tracking__pb2.GetTelemetryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rws_tracking.TrackingService/UpdateConfig',
            tracking__pb2.UpdateConfigRequest.SerializeToString,
            tracking__pb2.UpdateConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rws_tracking.TrackingService/StreamStatus',
            tracking__pb2.StreamStatusRequest.SerializeToString,
            tracking__pb2.StatusUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
